### ISSUE TITLE
Deprecate usage of MPI_MINLOC and MPI_MAXLOC with accumulate

### ISSUE THREAD

**Issue by hjelmn** [mpiwg-rma/rma-issues#2]
I am putting this out there to get comments. In my opinion these operations should not be part of the MPI standard let alone be used for RMA.

Reasons for deprecating:
- These operations require the usage of specific MPI datatypes. We have a small subset of them defined but we can imagine defining countless others. See mpi-forum/mpi-issues#18. It seems to me that due to the limited usefulness of these functions users are better off defining their own ops.
- A Google search returns mostly the definition of these operations. This suggests there is very limited usage (if any). If there is no usage there is little reason to maintain these as part of the standard. I very well could be wrong and there may be many codes making use of these operations.
- From my interpretation of the standard we can not modify the pad bits in types like MPI_SHORT_INT (the type that made me aware of these operations) so it takes code to support the non-contiguous predefined datatypes. I have to write the code which is why I am bringing this up.

Cons of deprecating:
- Some hardware vendors may already provide optimizations for these operations.
- There may be a much larger user base for these operations than a Google search suggests.

Again, this is more of an RFC than anything else.

**Comment by jeffhammond** [comment]
# Special Types

I agree that the situation with special types is horrible.  I have already proposed fixing that, as have @goodell and @jedbrown, as I recall.  I am too lazy to link those tickets here.

# Padding

I think it is more interesting to entertain the idea of allowing the pad bits to change, but of course that breaks backwards compatibility.  It's also largely unnecessary to consider this as an optimization, since the RMA atomicity rules are permissive and do not prevent a terrible software implementation of `MPI_SHORT_INT` from interfering with better ones for other type+op pairs.

# Usage

PETSc actually uses MAXLOC: 
- https://github.com/petsc/petsc/blob/39b82c7d1c912d939006869ea3efc1f41ed4eb9e/src/dm/impls/plex/plexsubmesh.c
- https://github.com/petsc/petsc/blob/39b82c7d1c912d939006869ea3efc1f41ed4eb9e/src/dm/impls/plex/plexcreate.c

I see nontrivial use on GitHub, looking only at Fortran codes (because that excludes e.g. most of the MPICH forks):
- https://github.com/search?l=fortran&p=1&q=MPI_MAXLOC&type=Code&utf8=%E2%9C%93

**Comment by hjelmn** [comment]
@jeffhammond Thanks. Lots of the hits look like they are in helper code (or fortran bindings) but there are indeed some users. I will have to look through them and evaluate the level of usage.

The other thing I intend to do is take some measurements of a user operation vs. MPI_MINLOC/MPI_MAXLOC with different implementations. I know we do not optimize either in Open MPI but CrayPICH or another implementation might.

**Comment by jeffhammond** [comment]
M**LOC is supported in [PAMI](https://bgq1.epfl.ch/navigator/resources/doc/pami/group__datatype__predefines__maxloc__minloc.html), which implies that there is at least an optimized _software_ implementation on Blue Gene/Q.  Whether or not it makes a different is TBD (`PAMID_COLLECTIVES={0,1}` is how one would test this).

Given that this breaks backwards compatibility of MPI-1 codes, we need a really good argument for deprecating it, and I'm not seeing any indication of one.

It would be more reasonable to consider deprecation of just `MPI_SHORT_INT` or changing the semantics to allow the implementation to touch the pad bits while the operation is in-flight, since I consider any application that relies on this semantic to be perverse.

**Comment by hjelmn** [comment]
@jeffhammond Agree on the pad bits. A little less so on not deprecating. If we indeed do break thinks in MPI-4 this might be worth considering. If we intend to limit the breakage then the pad bits or getting rid of all non-contiguous predefined types is the way to go.

**Comment by jeffhammond** [comment]
@hjelmn I recall that @jedbrown really likes MPI symmetry and was planning to use RMA and reductions identically, including M**LOC.

With respect to padding bits, we are only breaking the scenario when the user polls on `b` while MPI is touching `a` and `c` with M**LOC, right?
```c
struct {
 short a;
 short b;
 int c;
} my_short_short_int_t;
```

If necessary, I assume that `c` has the same offset in `my_short_short_int_t` as it does in the following.
```c
struct {
 short a;
 int c;
} my_short_int_t;
```

**Comment by jedbrown** [comment]
I used RMA for a graph communication implementation that I was once really excited about and had a clean mapping to MPI, but the limited type support (e.g., `M**LOC` with wider types and any operations with quad precision types) has ultimately forced us to eschew RMA for production code. (The alternate implementation is much less elegant, but actually working for all users is a great bonus.)  Note that the type support could be fixed by allowing user-defined Ops, but that basically yields active messages which has always been a non-starter with the Forum.  Anyway, `M**LOC` continue to be useful and I would use them with RMA if the type issues are resolved, but until then, I've accepted that there are plenty of desirable things that you just can't do with MPI's RMA due to type/op limitations. I filed some tickets circa 2012 when this was an active issue, but it might take some archaeology to dig up the Trac discussions.

**Comment by hjelmn** [comment]
@jeffhammond Exactly. Those two structures have the same offset for c. I don't see anything in MPI that explicitly forbids using my_short_short_int_t as an MPI_SHORT_INT. The only requirement is that the displacement of the int matches a datatype as far as I can tell. See MPI-3.1 p. 180 36-42.

I want to add one more reason the ops should go: The names of the types are odd. I know this is not a technical argument but still valid. I have probably mentioned before the most common response I get when I ask people what they think MPI_SHORT_INT represents is C's short int not struct {short a; int b;}. Looking at the list of predefined datatypes the pair types really do not fit when looking at the list of predefined datatypes.

Also, In an advice to users we actually recommend against creating struct types with holes. See MPI-3.1 p. 106 1-10. All the pair types have a chance of being non-contiguous type. It just happens that right now MPI_SHORT_INT is one under discussion. I assume on some current platforms MPI_FLOAT_INT could also be non-contiguous if ```sizeof (int) == 8``` and ```sizeof (float) == 4```. This problem goes away if we change the definition of those types to be contiguous and allow the MPI implementation to modify pad bits.

**Comment by hjelmn** [comment]
@jedbrown Thank you! I will have to do some digging to find it. What width data types do you need? I think we could support any operation if we expanded the definition of MPI_Compare_and_swap to allow any predefined datatype or a type created with MPI_Type_create_struct. You can build any atomic you want on top of that.

**Comment by jeffhammond** [comment]
CAS should only support built in types. We should not abuse CAS to implement things that we can implement directly.

**Comment by hjelmn** [comment]
Yeah, probably. Just the semantics are much cleaner than trying to support arrays of structs in MPI_Accumulate et al. Its just bytes to CAS.

**Comment by jedbrown** [comment]
@hjelmn Pair types with 64-bit ints, `__float128`, and `__complex128` would make RMA usable for us.

**Comment by hjelmn** [comment]
@jedbrown A user-defined op would definitely help with that. Could then use MPI_DOUBLE_COMPLEX as the datatype. @jeffhammond Do you know what the objection was to allowing user-defined operations with RMA?

**Comment by jeffhammond** [comment]
@hjelmn RMA needs to permit a hardware implementation to achieve the goal of supporting Global Arrays, SHMEM and PGAS languages effectively.  User-defined operations are active messages and cannot be implemented in an ASIC.

The right way to help @jedbrown is to show that Fortran 2008 has 128b floats in the language and we need to support them holistically in MPI.  From there, it's reasonable to discuss how these types are accessible from a C program.

It is more reasonable to extend the types that RMA supports than the ops...

**Comment by jedbrown** [comment]
@jeffhammond Meh, reductions also need to be done in hardware yet they allow user-defined Ops. I have yet to see a cogent argument that allowing user-defined Ops would ruin the performance of hardware-accelerated RMA Ops. My understanding is that active messages are seen by the Forum as a bit of a Pandora's box, particularly in terms of indirect consequences and failure modes. I think they are a simple and powerful primitive for building higher level abstractions, but understand the Forum's lack of enthusiasm. In any case, this will never be the use case that convinces the Forum to add active messages.

**Comment by jeffhammond** [comment]
@jedbrown There is a critical semantic difference between `MPI_Reduce` and `MPI_Accumulate` w.r.t. user-defined ops.  `MPI_Op_create` is local.  That means that target of RMA may not know anything about the op.  So it must be encoded in the message.  Now you have to send the op payload, convert to executable code at the target, and then use it.  No such thing is required for reductions.  Now, you can argue that we can just add something like `MPI_Win_op_create` that is collective, but   we still have no hope but to execute in software.

In any case, user-defined reductions are not implemented in hardware, but this in no way limits optimizations for built-in ops.  The key is that both can be implemented in a reasonable way.  On the other hand, what you are suggesting for RMA would force implementations to use an persistent asynchronous software agent, at least when `MPI_Win_op_create` is called, but the MPI Forum continues to work under the assumption that not all platforms provide threads.  Blue Gene/L in VN mode would be the most recent example of such a platform.

As for active messages, can you demonstrate a scenario where efficient use of Send+Probe+Recv are inadequate?

**Comment by jedbrown** [comment]
User-defined ops in reductions have no hope but to execute in software either. Collective creation or registration of an Op with a Comm or Win doesn't seem that hard to me. Are you aware of any hardware implementation of `MPI_Accumulate` with `MPI_M**LOC`, or of `MPI_PROD` on `MPI_C_COMPLEX`? If not, then the implementation has a way to process these in software (whether or not threads are available). There is no fundamental difference between whether that software implementation is packaged in libmpi or provided by user code.

User-defined nonblocking collectives cannot make progress without a dedicated progress thread if they rely on polling. The progress thread is a major liability if there is more than one such library involved. We've discussed this many times over the past few years and I totally get that the Forum is not going to add this capability, but that doesn't mean it isn't practically implementable or wouldn't offer useful capability.

**Comment by jeffhammond** [comment]
User-defined-op reductions can be done with hardware if `MPI_Op_create` involved your FPGA compiler stack 😄 

Hardware implementation of `MPI_Accumulate` with `MPI_M**LOC`, `MPI_PROD`, or gross types like `MPI_LONG_DOUBLE_COMPLEX` is not required, because the RMA memory model makes it feasible to do op+type pairs that people actually use in hardware and other ones in software.  

Anyways, one can in fact implement your examples without any asynchronous software agent by emulating atomics with compare-and-swap or lock-get-compute-put-unlock.  For example, a shared-memory implementation of RMA can do any atomic on 128b types with `CMPXCHG16B`.  Similarly, an MPI implementation can emulate `MPI_PROD` with compare-and-swap on any network that supports the latter.

In contrast, unless you restrict the active-message handler to act only on data in the window+payload, user-defined code is not necessarily feasible.  Consider, for example, MPMD applications where the callback uses a function that is only defined in the binary at the target.  One cannot do lock-get-compute-put-unlock here.

**Comment by hjelmn** [comment]
@jeffhammond Open MPI's accumulate operation is a lock-get-op-put-unlock operation if an atomic is not available. This code path is fine for user ops as well. I could enable them with a couple lines of code. Certainly the user can implement this or get-op-cas in their software but the code paths already exist in Open MPI so it would be silly to not allow the user to use them with their own op IMO.

**Comment by jedbrown** [comment]
@jeffhammond  The point of collectively registering an Op is to be able to refer to the implementation defined at the target. And reduction Ops already make purity assumptions, so that's nothing new. (If your reduction Op has side-effects, the behavior is undefined.) Anyway, it sounds like you're agreeing with me that it would indeed be possible to support user-defined Ops for RMA without degrading the performance of builtins, and are merely reiterating that user-defined Ops need to be well-defined at the target and must respect the natural contract about purity.  I also understand that the Forum isn't interested.

@hjelmn It doesn't really matter whether Open MPI could easily implement active messages.

**Comment by jeffhammond** [comment]
@hjelmn I assume you would require a collective op_create routine and assume homogeneous SPMD execution.  And if you rely on CAS, you can only do operations that act on a single element at a time, which might not be useful.

It is useful to imagine how you would support all of GASNet in MPI RMA, because that is what some users will expect if you promise them active-messages.

**Comment by jeffhammond** [comment]
@jedbrown Well, the author list of http://www.mcs.anl.gov/~thakur/papers/mpi-active-messages.pdf includes a number of members of the MPI Forum, so I would not say that it isn't of interest.  However, unlike one-sided communication, there is not a clear consensus on what can be implemented efficiently and portably in the context of active-messages.

I have attempted to convince the MPI Forum that we should _assume_ threads for MPI-4 and beyond, which has some impact on how we support thread-safety.  If we cross that bridge, then we are in a position to stop using legacy systems like Blue Gene/L and the Earth Simulator as reasons for vetoing certain features that those platforms could not support.

However, there is still a desire with the RMA working group to have an implementation that _can_ be implemented in an ASIC.

When I proposed `MPI_Recv_reduce`/`MPI_Recv_accumulate`, one of my goals was to make it easier to do active-messages, but assuming explicit polling, which dramatically reduced the implementation complexity.  Unfortunately, there were some serious challenges with user-defined datatypes, which are complicated enough that I don't want to try to write them down here.

**Comment by hjelmn** [comment]
I am not thinking of an active message implementation. When network RDMA is available the op is completely executed on the origin which does not require collective op creation. It is a little more difficult for the osc/pt2pt (osc over send/recv) component but I could implement something similar. It would not be performant but that component is not meant to be. I agree it is kind of a mess but it might be useful.

It might still be better to have the user implement it themselves with lock-get-op-put-unlock or a get-op-cas loop.

**Comment by devreal** [comment]
Closing this, as it has been out there and been supported by implementations.

**Comment by jdinan** [comment]
As a breadcrumb, Scalasca uses min/max-loc atomics to coordinate timestamps. Given that it's already used, the decision was made at the 2/1/22 WG meeting not to deprecate unless a very strong rationale for deprecation can be given.

**Comment by hjelmn** [comment]
Can we at least deal with the padding bits? MPI_SHORT_INT was a terrible idea from the start but it we can make it explicit that there are no guarantees on the pad bits (C/C++ already has this) then I don't really care as much. The issue came up because that horrible horrible built-in datatype is non-contiguous on all modern hardware.

**Comment by jdinan** [comment]
Agree. We should clarify that MPI makes no guarantees on padding bytes for pair types, as well as for structure types. Could you file a separate issue for this?

**Comment by jdinan** [comment]
It seems kind of important, e.g. for an all-reduce, that the padding in MPI_SHORT_INT need not be identical at all processes.

**Comment by devreal** [comment]
@hjelmn 
> Can we at least deal with the padding bits? MPI_SHORT_INT was a terrible idea from the start but it we can make it explicit that there are no guarantees on the pad bits (C/C++ already has this) then I don't really care as much. The issue came up because that horrible horrible built-in datatype is non-contiguous on all modern hardware.

Just to clarify, we should specify that there are no guarantees about padding bytes in pair types, right? Isn't that inherited from the base language?
